---
title: "Stats - Tempo"
---

Load libraries
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
```

Read in the data
```{r}
reg_season_stats <- read.csv("data/Prelim2019_RegularSeasonDetailedResults.csv", stringsAsFactors = FALSE)
tourney_stats <- read.csv("data/NCAATourneyDetailedResults.csv", stringsAsFactors = FALSE)
#preview data
head(reg_season_stats)
tail(reg_season_stats)
head(tourney_stats)
tail(tourney_stats)
```

Combine regular season and tournament
```{r}
#distinguish between season and tournament games (no longer needed)
reg_season_stats$post <- 0
tourney_stats$post <- 1
#combine
combined_stats <- bind_rows(reg_season_stats, tourney_stats)
```

Compute tempo per game for winning and losing teams
```{r}
combined_stats <- combined_stats %>% mutate(Wposs = WFGA - WOR + WTO + 0.475*WFTA)
combined_stats <- combined_stats %>% mutate(Lposs = LFGA - LOR + LTO + 0.475*LFTA)
head(combined_stats)
```

Combine winning teams and losing teams stats
```{r}
#duplicate data
combined_statsCompiled <- combined_stats

#change the column names so that they are identical for merging
names(combined_statsCompiled) <- gsub(x = names(combined_statsCompiled), pattern = "WTeam", replacement = "Team")
names(combined_statsCompiled) <- gsub(x = names(combined_statsCompiled), pattern = "LTeam", replacement = "Team")
names(combined_statsCompiled) <- gsub(x = names(combined_statsCompiled), pattern = "W", replacement = "")
names(combined_statsCompiled) <- gsub(x = names(combined_statsCompiled), pattern = "L", replacement = "")

#combine WTeam and LTeam stats
combined_statsCompiled <- bind_rows(combined_statsCompiled[,c(1,3:4,9:21,35,36)],combined_statsCompiled[,c(1,5:6,22:34,35,37)])
head(combined_statsCompiled)
```

Compute average tempo over season
```{r}
#find all unique values by BOTH Season and TeamID
#this will be the skeleton of the final database we want
combined_statsCompiledUnique <- distinct(combined_statsCompiled,Season, TeamID, .keep_all = TRUE)
combined_statsCompiledUnique <- combined_statsCompiledUnique %>% select(Season, TeamID,  poss)

#loop through all the unique values
for (i in 1:NROW(combined_statsCompiledUnique)){
    #we want to replace the per game data in each row of the unique data frame with tempo for that team in that season
    #first filter the FULL season results by two variables, the current row SEASON and TEAM ID
    #then only select the rows where tempo can be computed
    #compute the tempo and insert into the respective row of the unique data frame
    combined_statsCompiledUnique[i,c(3)] <- colMeans(combined_statsCompiled %>%
      filter(Season == combined_statsCompiledUnique[i,1], TeamID == combined_statsCompiledUnique[i,2]) %>%
      dplyr::select(c(poss)))
}
```

Rename variable
```{r}
names(combined_statsCompiledUnique)[3] <- "tempo"
head(combined_statsCompiledUnique)
tail(combined_statsCompiledUnique)
```

Output to file
```{r}
write.csv(combined_statsCompiledUnique, file="output/stats-tempo.csv", row.names = FALSE)
```


